<?xml version="1.0" encoding="utf-8"?><Database Name="ManavDB" Class="DataManavDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ALS-YG39104-J03;Initial Catalog=ManavDB;Persist Security Info=True;User ID=sa" SettingsObjectName="manav1.Properties.Settings" SettingsPropertyName="ManavDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Manav" Member="tbl_Manavs">
    <Type Name="tbl_Manav">
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>